package com.yasiradnan.conference;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.SqlUtils;

import com.yasiradnan.conference.AbstractAuthor;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ABSTRACT_AUTHOR.
*/
public class AbstractAuthorDao extends AbstractDao<AbstractAuthor, Long> {

    public static final String TABLENAME = "ABSTRACT_AUTHOR";

    /**
     * Properties of entity AbstractAuthor.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Is_Corresponding = new Property(2, Boolean.class, "Is_Corresponding", false, "IS__CORRESPONDING");
        public final static Property AbstractsitemId = new Property(3, Long.class, "abstractsitemId", false, "ABSTRACTSITEM_ID");
        public final static Property AbsAffiliationId = new Property(4, Long.class, "absAffiliationId", false, "ABS_AFFILIATION_ID");
    };

    private DaoSession daoSession;


    public AbstractAuthorDao(DaoConfig config) {
        super(config);
    }
    
    public AbstractAuthorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ABSTRACT_AUTHOR' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NAME' TEXT NOT NULL ," + // 1: name
                "'IS__CORRESPONDING' INTEGER," + // 2: Is_Corresponding
                "'ABSTRACTSITEM_ID' INTEGER," + // 3: abstractsitemId
                "'ABS_AFFILIATION_ID' INTEGER);"); // 4: absAffiliationId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ABSTRACT_AUTHOR'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AbstractAuthor entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
 
        Boolean Is_Corresponding = entity.getIs_Corresponding();
        if (Is_Corresponding != null) {
            stmt.bindLong(3, Is_Corresponding ? 1l: 0l);
        }
 
        Long abstractsitemId = entity.getAbstractsitemId();
        if (abstractsitemId != null) {
            stmt.bindLong(4, abstractsitemId);
        }
 
        Long absAffiliationId = entity.getAbsAffiliationId();
        if (absAffiliationId != null) {
            stmt.bindLong(5, absAffiliationId);
        }
    }

    @Override
    protected void attachEntity(AbstractAuthor entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public AbstractAuthor readEntity(Cursor cursor, int offset) {
        AbstractAuthor entity = new AbstractAuthor( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0, // Is_Corresponding
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // abstractsitemId
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // absAffiliationId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AbstractAuthor entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setIs_Corresponding(cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0);
        entity.setAbstractsitemId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setAbsAffiliationId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(AbstractAuthor entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(AbstractAuthor entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getAbstractsItemDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getAbstractAffiliationDao().getAllColumns());
            builder.append(" FROM ABSTRACT_AUTHOR T");
            builder.append(" LEFT JOIN ABSTRACTS_ITEM T0 ON T.'ABSTRACTSITEM_ID'=T0.'_id'");
            builder.append(" LEFT JOIN ABSTRACT_AFFILIATION T1 ON T.'ABS_AFFILIATION_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected AbstractAuthor loadCurrentDeep(Cursor cursor, boolean lock) {
        AbstractAuthor entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        AbstractsItem abstractsItem = loadCurrentOther(daoSession.getAbstractsItemDao(), cursor, offset);
        entity.setAbstractsItem(abstractsItem);
        offset += daoSession.getAbstractsItemDao().getAllColumns().length;

        AbstractAffiliation abstractAffiliation = loadCurrentOther(daoSession.getAbstractAffiliationDao(), cursor, offset);
        entity.setAbstractAffiliation(abstractAffiliation);

        return entity;    
    }

    public AbstractAuthor loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<AbstractAuthor> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<AbstractAuthor> list = new ArrayList<AbstractAuthor>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<AbstractAuthor> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<AbstractAuthor> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
