package com.yasiradnan.conference;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.SqlUtils;

import com.yasiradnan.conference.AbstractAffiliation;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ABSTRACT_AFFILIATION.
*/
public class AbstractAffiliationDao extends AbstractDao<AbstractAffiliation, Long> {

    public static final String TABLENAME = "ABSTRACT_AFFILIATION";

    /**
     * Properties of entity AbstractAffiliation.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AffiliationNumber = new Property(1, Integer.class, "affiliationNumber", false, "AFFILIATION_NUMBER");
        public final static Property AbsAuthorId = new Property(2, long.class, "absAuthorId", false, "ABS_AUTHOR_ID");
    };

    private DaoSession daoSession;


    public AbstractAffiliationDao(DaoConfig config) {
        super(config);
    }
    
    public AbstractAffiliationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ABSTRACT_AFFILIATION' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'AFFILIATION_NUMBER' INTEGER," + // 1: affiliationNumber
                "'ABS_AUTHOR_ID' INTEGER NOT NULL );"); // 2: absAuthorId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ABSTRACT_AFFILIATION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AbstractAffiliation entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer affiliationNumber = entity.getAffiliationNumber();
        if (affiliationNumber != null) {
            stmt.bindLong(2, affiliationNumber);
        }
        stmt.bindLong(3, entity.getAbsAuthorId());
    }

    @Override
    protected void attachEntity(AbstractAffiliation entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public AbstractAffiliation readEntity(Cursor cursor, int offset) {
        AbstractAffiliation entity = new AbstractAffiliation( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // affiliationNumber
            cursor.getLong(offset + 2) // absAuthorId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AbstractAffiliation entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAffiliationNumber(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setAbsAuthorId(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(AbstractAffiliation entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(AbstractAffiliation entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getAbstractAuthorDao().getAllColumns());
            builder.append(" FROM ABSTRACT_AFFILIATION T");
            builder.append(" LEFT JOIN ABSTRACT_AUTHOR T0 ON T.'ABS_AUTHOR_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected AbstractAffiliation loadCurrentDeep(Cursor cursor, boolean lock) {
        AbstractAffiliation entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        AbstractAuthor abstractAuthor = loadCurrentOther(daoSession.getAbstractAuthorDao(), cursor, offset);
         if(abstractAuthor != null) {
            entity.setAbstractAuthor(abstractAuthor);
        }

        return entity;    
    }

    public AbstractAffiliation loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<AbstractAffiliation> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<AbstractAffiliation> list = new ArrayList<AbstractAffiliation>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<AbstractAffiliation> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<AbstractAffiliation> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
