package com.yasiradnan.conference;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ABSTRACT_AUTHOR.
 */
public class AbstractAuthor {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String is_Corresponding;

    public AbstractAuthor() {
    }

    public AbstractAuthor(Long id) {
        this.id = id;
    }

    public AbstractAuthor(Long id, String name, String is_Corresponding) {
        this.id = id;
        this.name = name;
        this.is_Corresponding = is_Corresponding;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getIs_Corresponding() {
        return is_Corresponding;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIs_Corresponding(String is_Corresponding) {
        this.is_Corresponding = is_Corresponding;
    }

}
