package com.yasiradnan.conference;

import com.yasiradnan.conference.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ABSTRACT_KEY_WORDS.
 */
public class AbstractKeyWords {

    private String keywords;
    private long abstractsitemId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient AbstractKeyWordsDao myDao;

    private AbstractsItem abstractsItem;
    private Long abstractsItem__resolvedKey;


    public AbstractKeyWords() {
    }

    public AbstractKeyWords(String keywords, long abstractsitemId) {
        this.keywords = keywords;
        this.abstractsitemId = abstractsitemId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getAbstractKeyWordsDao() : null;
    }

    public String getKeywords() {
        return keywords;
    }

    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    public long getAbstractsitemId() {
        return abstractsitemId;
    }

    public void setAbstractsitemId(long abstractsitemId) {
        this.abstractsitemId = abstractsitemId;
    }

    /** To-one relationship, resolved on first access. */
    public AbstractsItem getAbstractsItem() {
        if (abstractsItem__resolvedKey == null || !abstractsItem__resolvedKey.equals(abstractsitemId)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            AbstractsItemDao targetDao = daoSession.getAbstractsItemDao();
            abstractsItem = targetDao.load(abstractsitemId);
            abstractsItem__resolvedKey = abstractsitemId;
        }
        return abstractsItem;
    }

    public void setAbstractsItem(AbstractsItem abstractsItem) {
        if (abstractsItem == null) {
            throw new DaoException("To-one property 'abstractsitemId' has not-null constraint; cannot set to-one to null");
        }
        this.abstractsItem = abstractsItem;
        abstractsitemId = abstractsItem.getId();
        abstractsItem__resolvedKey = abstractsitemId;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
