package com.yasiradnan.conference;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.SqlUtils;

import com.yasiradnan.conference.AbstractAffiliateName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ABSTRACT_AFFILIATE_NAME.
*/
public class AbstractAffiliateNameDao extends AbstractDao<AbstractAffiliateName, Void> {

    public static final String TABLENAME = "ABSTRACT_AFFILIATE_NAME";

    /**
     * Properties of entity AbstractAffiliateName.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property AbstractsitemId = new Property(0, long.class, "abstractsitemId", false, "ABSTRACTSITEM_ID");
        public final static Property AbsaffiliationnameId = new Property(1, long.class, "absaffiliationnameId", false, "ABSAFFILIATIONNAME_ID");
    };

    private DaoSession daoSession;


    public AbstractAffiliateNameDao(DaoConfig config) {
        super(config);
    }
    
    public AbstractAffiliateNameDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ABSTRACT_AFFILIATE_NAME' (" + //
                "'ABSTRACTSITEM_ID' INTEGER NOT NULL ," + // 0: abstractsitemId
                "'ABSAFFILIATIONNAME_ID' INTEGER NOT NULL );"); // 1: absaffiliationnameId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ABSTRACT_AFFILIATE_NAME'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AbstractAffiliateName entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getAbstractsitemId());
        stmt.bindLong(2, entity.getAbsaffiliationnameId());
    }

    @Override
    protected void attachEntity(AbstractAffiliateName entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public AbstractAffiliateName readEntity(Cursor cursor, int offset) {
        AbstractAffiliateName entity = new AbstractAffiliateName( //
            cursor.getLong(offset + 0), // abstractsitemId
            cursor.getLong(offset + 1) // absaffiliationnameId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AbstractAffiliateName entity, int offset) {
        entity.setAbstractsitemId(cursor.getLong(offset + 0));
        entity.setAbsaffiliationnameId(cursor.getLong(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(AbstractAffiliateName entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(AbstractAffiliateName entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getAbstractsItemDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getAbsAffiliationNameDao().getAllColumns());
            builder.append(" FROM ABSTRACT_AFFILIATE_NAME T");
            builder.append(" LEFT JOIN ABSTRACTS_ITEM T0 ON T.'ABSTRACTSITEM_ID'=T0.'_id'");
            builder.append(" LEFT JOIN ABS_AFFILIATION_NAME T1 ON T.'ABSAFFILIATIONNAME_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected AbstractAffiliateName loadCurrentDeep(Cursor cursor, boolean lock) {
        AbstractAffiliateName entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        AbstractsItem abstractsItem = loadCurrentOther(daoSession.getAbstractsItemDao(), cursor, offset);
         if(abstractsItem != null) {
            entity.setAbstractsItem(abstractsItem);
        }
        offset += daoSession.getAbstractsItemDao().getAllColumns().length;

        AbsAffiliationName absAffiliationName = loadCurrentOther(daoSession.getAbsAffiliationNameDao(), cursor, offset);
         if(absAffiliationName != null) {
            entity.setAbsAffiliationName(absAffiliationName);
        }

        return entity;    
    }

    public AbstractAffiliateName loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<AbstractAffiliateName> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<AbstractAffiliateName> list = new ArrayList<AbstractAffiliateName>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<AbstractAffiliateName> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<AbstractAffiliateName> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
