package com.yasiradnan.conference;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.SqlUtils;

import com.yasiradnan.conference.AbstractKeyWords;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ABSTRACT_KEY_WORDS.
*/
public class AbstractKeyWordsDao extends AbstractDao<AbstractKeyWords, Void> {

    public static final String TABLENAME = "ABSTRACT_KEY_WORDS";

    /**
     * Properties of entity AbstractKeyWords.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Keywords = new Property(0, String.class, "keywords", false, "KEYWORDS");
        public final static Property AbstractsitemId = new Property(1, long.class, "abstractsitemId", false, "ABSTRACTSITEM_ID");
    };

    private DaoSession daoSession;


    public AbstractKeyWordsDao(DaoConfig config) {
        super(config);
    }
    
    public AbstractKeyWordsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ABSTRACT_KEY_WORDS' (" + //
                "'KEYWORDS' TEXT," + // 0: keywords
                "'ABSTRACTSITEM_ID' INTEGER NOT NULL );"); // 1: abstractsitemId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ABSTRACT_KEY_WORDS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AbstractKeyWords entity) {
        stmt.clearBindings();
 
        String keywords = entity.getKeywords();
        if (keywords != null) {
            stmt.bindString(1, keywords);
        }
        stmt.bindLong(2, entity.getAbstractsitemId());
    }

    @Override
    protected void attachEntity(AbstractKeyWords entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public AbstractKeyWords readEntity(Cursor cursor, int offset) {
        AbstractKeyWords entity = new AbstractKeyWords( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // keywords
            cursor.getLong(offset + 1) // abstractsitemId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AbstractKeyWords entity, int offset) {
        entity.setKeywords(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setAbstractsitemId(cursor.getLong(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(AbstractKeyWords entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(AbstractKeyWords entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getAbstractsItemDao().getAllColumns());
            builder.append(" FROM ABSTRACT_KEY_WORDS T");
            builder.append(" LEFT JOIN ABSTRACTS_ITEM T0 ON T.'ABSTRACTSITEM_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected AbstractKeyWords loadCurrentDeep(Cursor cursor, boolean lock) {
        AbstractKeyWords entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        AbstractsItem abstractsItem = loadCurrentOther(daoSession.getAbstractsItemDao(), cursor, offset);
         if(abstractsItem != null) {
            entity.setAbstractsItem(abstractsItem);
        }

        return entity;    
    }

    public AbstractKeyWords loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<AbstractKeyWords> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<AbstractKeyWords> list = new ArrayList<AbstractKeyWords>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<AbstractKeyWords> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<AbstractKeyWords> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
