package com.yasiradnan.conference;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ABSTRACT_AFFILIATION.
 */
public class AbstractAffiliation {

    private Long id;
    private String affiliationNumber;

    public AbstractAffiliation() {
    }

    public AbstractAffiliation(Long id) {
        this.id = id;
    }

    public AbstractAffiliation(Long id, String affiliationNumber) {
        this.id = id;
        this.affiliationNumber = affiliationNumber;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAffiliationNumber() {
        return affiliationNumber;
    }

    public void setAffiliationNumber(String affiliationNumber) {
        this.affiliationNumber = affiliationNumber;
    }

}
