package com.yasiradnan.conference;

import com.yasiradnan.conference.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table AUTHORS_ABSTRACT.
 */
public class AuthorsAbstract {

    private long abstractsitemId;
    private long abstractauthorId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient AuthorsAbstractDao myDao;

    private AbstractsItem abstractsItem;
    private Long abstractsItem__resolvedKey;

    private AbstractAuthor abstractAuthor;
    private Long abstractAuthor__resolvedKey;


    public AuthorsAbstract() {
    }

    public AuthorsAbstract(long abstractsitemId, long abstractauthorId) {
        this.abstractsitemId = abstractsitemId;
        this.abstractauthorId = abstractauthorId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getAuthorsAbstractDao() : null;
    }

    public long getAbstractsitemId() {
        return abstractsitemId;
    }

    public void setAbstractsitemId(long abstractsitemId) {
        this.abstractsitemId = abstractsitemId;
    }

    public long getAbstractauthorId() {
        return abstractauthorId;
    }

    public void setAbstractauthorId(long abstractauthorId) {
        this.abstractauthorId = abstractauthorId;
    }

    /** To-one relationship, resolved on first access. */
    public AbstractsItem getAbstractsItem() {
        if (abstractsItem__resolvedKey == null || !abstractsItem__resolvedKey.equals(abstractsitemId)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            AbstractsItemDao targetDao = daoSession.getAbstractsItemDao();
            abstractsItem = targetDao.load(abstractsitemId);
            abstractsItem__resolvedKey = abstractsitemId;
        }
        return abstractsItem;
    }

    public void setAbstractsItem(AbstractsItem abstractsItem) {
        if (abstractsItem == null) {
            throw new DaoException("To-one property 'abstractsitemId' has not-null constraint; cannot set to-one to null");
        }
        this.abstractsItem = abstractsItem;
        abstractsitemId = abstractsItem.getId();
        abstractsItem__resolvedKey = abstractsitemId;
    }

    /** To-one relationship, resolved on first access. */
    public AbstractAuthor getAbstractAuthor() {
        if (abstractAuthor__resolvedKey == null || !abstractAuthor__resolvedKey.equals(abstractauthorId)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            AbstractAuthorDao targetDao = daoSession.getAbstractAuthorDao();
            abstractAuthor = targetDao.load(abstractauthorId);
            abstractAuthor__resolvedKey = abstractauthorId;
        }
        return abstractAuthor;
    }

    public void setAbstractAuthor(AbstractAuthor abstractAuthor) {
        if (abstractAuthor == null) {
            throw new DaoException("To-one property 'abstractauthorId' has not-null constraint; cannot set to-one to null");
        }
        this.abstractAuthor = abstractAuthor;
        abstractauthorId = abstractAuthor.getId();
        abstractAuthor__resolvedKey = abstractauthorId;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
