package com.yasiradnan.conference;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.IdentityScopeType;

import com.yasiradnan.conference.AbstractsItemDao;
import com.yasiradnan.conference.AbstractKeyWordsDao;
import com.yasiradnan.conference.AbstractAuthorDao;
import com.yasiradnan.conference.AbstractAffiliationDao;
import com.yasiradnan.conference.AbsAffiliationNameDao;
import com.yasiradnan.conference.AuthorsAbstractDao;
import com.yasiradnan.conference.AbstractAffiliateNameDao;
import com.yasiradnan.conference.AuthorsAffiliateDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        AbstractsItemDao.createTable(db, ifNotExists);
        AbstractKeyWordsDao.createTable(db, ifNotExists);
        AbstractAuthorDao.createTable(db, ifNotExists);
        AbstractAffiliationDao.createTable(db, ifNotExists);
        AbsAffiliationNameDao.createTable(db, ifNotExists);
        AuthorsAbstractDao.createTable(db, ifNotExists);
        AbstractAffiliateNameDao.createTable(db, ifNotExists);
        AuthorsAffiliateDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        AbstractsItemDao.dropTable(db, ifExists);
        AbstractKeyWordsDao.dropTable(db, ifExists);
        AbstractAuthorDao.dropTable(db, ifExists);
        AbstractAffiliationDao.dropTable(db, ifExists);
        AbsAffiliationNameDao.dropTable(db, ifExists);
        AuthorsAbstractDao.dropTable(db, ifExists);
        AbstractAffiliateNameDao.dropTable(db, ifExists);
        AuthorsAffiliateDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(AbstractsItemDao.class);
        registerDaoClass(AbstractKeyWordsDao.class);
        registerDaoClass(AbstractAuthorDao.class);
        registerDaoClass(AbstractAffiliationDao.class);
        registerDaoClass(AbsAffiliationNameDao.class);
        registerDaoClass(AuthorsAbstractDao.class);
        registerDaoClass(AbstractAffiliateNameDao.class);
        registerDaoClass(AuthorsAffiliateDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
